/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthenticatedAdminRouteImport } from './routes/authenticated/admin'
import { Route as AuthenticatedHelpRouteImport } from './routes/authenticated/help'
import { Route as AuthenticatedSettingsRouteImport } from './routes/authenticated/settings'
import { Route as AuthenticatedStudentRouteImport } from './routes/authenticated/student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/authenticated/teacher'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/authenticated/admin/notifications'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/authenticated/admin/students'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/authenticated/admin/teachers'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/authenticated/settings/appearance'
import { Route as AuthenticatedSettingsBellRouteImport } from './routes/authenticated/settings/bell'
import { Route as AuthenticatedSettingsHomeRouteImport } from './routes/authenticated/settings/home'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/authenticated/settings/password'
import { Route as AuthenticatedSettingsPrivacySecurityRouteImport } from './routes/authenticated/settings/privacy-security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/authenticated/settings/profile'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/authenticated/users/$userId'
import { Route as AuthenticatedSettingsAppearanceAccentRouteImport } from './routes/authenticated/settings/appearance/accent'
import { Route as AuthenticatedSettingsAppearanceFontRouteImport } from './routes/authenticated/settings/appearance/font'
import { Route as AuthenticatedSettingsAppearanceRadiusRouteImport } from './routes/authenticated/settings/appearance/radius'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBellRoute =
  AuthenticatedSettingsBellRouteImport.update({
    id: '/bell',
    path: '/bell',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHomeRoute =
  AuthenticatedSettingsHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPrivacySecurityRoute =
  AuthenticatedSettingsPrivacySecurityRouteImport.update({
    id: '/privacy-security',
    path: '/privacy-security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAppearanceAccentRoute =
  AuthenticatedSettingsAppearanceAccentRouteImport.update({
    id: '/accent',
    path: '/accent',
    getParentRoute: () => AuthenticatedSettingsAppearanceRoute,
  } as any)
const AuthenticatedSettingsAppearanceFontRoute =
  AuthenticatedSettingsAppearanceFontRouteImport.update({
    id: '/font',
    path: '/font',
    getParentRoute: () => AuthenticatedSettingsAppearanceRoute,
  } as any)
const AuthenticatedSettingsAppearanceRadiusRoute =
  AuthenticatedSettingsAppearanceRadiusRouteImport.update({
    id: '/radius',
    path: '/radius',
    getParentRoute: () => AuthenticatedSettingsAppearanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRouteWithChildren
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/privacy-security': typeof AuthenticatedSettingsPrivacySecurityRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/authenticated/settings/appearance/accent': typeof AuthenticatedSettingsAppearanceAccentRoute
  '/authenticated/settings/appearance/font': typeof AuthenticatedSettingsAppearanceFontRoute
  '/authenticated/settings/appearance/radius': typeof AuthenticatedSettingsAppearanceRadiusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRouteWithChildren
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/privacy-security': typeof AuthenticatedSettingsPrivacySecurityRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/authenticated/settings/appearance/accent': typeof AuthenticatedSettingsAppearanceAccentRoute
  '/authenticated/settings/appearance/font': typeof AuthenticatedSettingsAppearanceFontRoute
  '/authenticated/settings/appearance/radius': typeof AuthenticatedSettingsAppearanceRadiusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRouteWithChildren
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/privacy-security': typeof AuthenticatedSettingsPrivacySecurityRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/authenticated/settings/appearance/accent': typeof AuthenticatedSettingsAppearanceAccentRoute
  '/authenticated/settings/appearance/font': typeof AuthenticatedSettingsAppearanceFontRoute
  '/authenticated/settings/appearance/radius': typeof AuthenticatedSettingsAppearanceRadiusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/authenticated/admin'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/admin/notifications'
    | '/authenticated/admin/students'
    | '/authenticated/admin/teachers'
    | '/authenticated/settings/account'
    | '/authenticated/settings/appearance'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/privacy-security'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
    | '/authenticated/settings/appearance/accent'
    | '/authenticated/settings/appearance/font'
    | '/authenticated/settings/appearance/radius'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/authenticated/admin'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/admin/notifications'
    | '/authenticated/admin/students'
    | '/authenticated/admin/teachers'
    | '/authenticated/settings/account'
    | '/authenticated/settings/appearance'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/privacy-security'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
    | '/authenticated/settings/appearance/accent'
    | '/authenticated/settings/appearance/font'
    | '/authenticated/settings/appearance/radius'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/authenticated/admin'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/admin/notifications'
    | '/authenticated/admin/students'
    | '/authenticated/admin/teachers'
    | '/authenticated/settings/account'
    | '/authenticated/settings/appearance'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/privacy-security'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
    | '/authenticated/settings/appearance/accent'
    | '/authenticated/settings/appearance/font'
    | '/authenticated/settings/appearance/radius'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/authenticated/admin': {
      id: '/authenticated/admin'
      path: '/admin'
      fullPath: '/authenticated/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/help': {
      id: '/authenticated/help'
      path: '/help'
      fullPath: '/authenticated/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/settings': {
      id: '/authenticated/settings'
      path: '/settings'
      fullPath: '/authenticated/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/student': {
      id: '/authenticated/student'
      path: '/student'
      fullPath: '/authenticated/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/teacher': {
      id: '/authenticated/teacher'
      path: '/teacher'
      fullPath: '/authenticated/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/admin/notifications': {
      id: '/authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/authenticated/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/admin/students': {
      id: '/authenticated/admin/students'
      path: '/students'
      fullPath: '/authenticated/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/admin/teachers': {
      id: '/authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/authenticated/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/settings/account': {
      id: '/authenticated/settings/account'
      path: '/account'
      fullPath: '/authenticated/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/appearance': {
      id: '/authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/authenticated/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/bell': {
      id: '/authenticated/settings/bell'
      path: '/bell'
      fullPath: '/authenticated/settings/bell'
      preLoaderRoute: typeof AuthenticatedSettingsBellRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/home': {
      id: '/authenticated/settings/home'
      path: '/home'
      fullPath: '/authenticated/settings/home'
      preLoaderRoute: typeof AuthenticatedSettingsHomeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/password': {
      id: '/authenticated/settings/password'
      path: '/password'
      fullPath: '/authenticated/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/privacy-security': {
      id: '/authenticated/settings/privacy-security'
      path: '/privacy-security'
      fullPath: '/authenticated/settings/privacy-security'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacySecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/profile': {
      id: '/authenticated/settings/profile'
      path: '/profile'
      fullPath: '/authenticated/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/users/$userId': {
      id: '/authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/authenticated/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/settings/appearance/accent': {
      id: '/authenticated/settings/appearance/accent'
      path: '/accent'
      fullPath: '/authenticated/settings/appearance/accent'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceAccentRouteImport
      parentRoute: typeof AuthenticatedSettingsAppearanceRoute
    }
    '/authenticated/settings/appearance/font': {
      id: '/authenticated/settings/appearance/font'
      path: '/font'
      fullPath: '/authenticated/settings/appearance/font'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceFontRouteImport
      parentRoute: typeof AuthenticatedSettingsAppearanceRoute
    }
    '/authenticated/settings/appearance/radius': {
      id: '/authenticated/settings/appearance/radius'
      path: '/radius'
      fullPath: '/authenticated/settings/appearance/radius'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRadiusRouteImport
      parentRoute: typeof AuthenticatedSettingsAppearanceRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsAppearanceRouteChildren {
  AuthenticatedSettingsAppearanceAccentRoute: typeof AuthenticatedSettingsAppearanceAccentRoute
  AuthenticatedSettingsAppearanceFontRoute: typeof AuthenticatedSettingsAppearanceFontRoute
  AuthenticatedSettingsAppearanceRadiusRoute: typeof AuthenticatedSettingsAppearanceRadiusRoute
}

const AuthenticatedSettingsAppearanceRouteChildren: AuthenticatedSettingsAppearanceRouteChildren =
  {
    AuthenticatedSettingsAppearanceAccentRoute:
      AuthenticatedSettingsAppearanceAccentRoute,
    AuthenticatedSettingsAppearanceFontRoute:
      AuthenticatedSettingsAppearanceFontRoute,
    AuthenticatedSettingsAppearanceRadiusRoute:
      AuthenticatedSettingsAppearanceRadiusRoute,
  }

const AuthenticatedSettingsAppearanceRouteWithChildren =
  AuthenticatedSettingsAppearanceRoute._addFileChildren(
    AuthenticatedSettingsAppearanceRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRouteWithChildren
  AuthenticatedSettingsBellRoute: typeof AuthenticatedSettingsBellRoute
  AuthenticatedSettingsHomeRoute: typeof AuthenticatedSettingsHomeRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsPrivacySecurityRoute: typeof AuthenticatedSettingsPrivacySecurityRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppearanceRoute:
    AuthenticatedSettingsAppearanceRouteWithChildren,
  AuthenticatedSettingsBellRoute: AuthenticatedSettingsBellRoute,
  AuthenticatedSettingsHomeRoute: AuthenticatedSettingsHomeRoute,
  AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
  AuthenticatedSettingsPrivacySecurityRoute:
    AuthenticatedSettingsPrivacySecurityRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
