/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/authenticated'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthenticatedBellRouteImport } from './routes/authenticated/bell'
import { Route as AuthenticatedHelpRouteImport } from './routes/authenticated/help'
import { Route as AuthenticatedSettingsRouteImport } from './routes/authenticated/settings'
import { Route as AuthenticatedStudentRouteImport } from './routes/authenticated/student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/authenticated/teacher'
import { Route as AuthenticatedSettingsBellRouteImport } from './routes/authenticated/settings/bell'
import { Route as AuthenticatedSettingsHomeRouteImport } from './routes/authenticated/settings/home'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/authenticated/settings/password'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/authenticated/settings/profile'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/authenticated/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedBellRoute = AuthenticatedBellRouteImport.update({
  id: '/bell',
  path: '/bell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsBellRoute =
  AuthenticatedSettingsBellRouteImport.update({
    id: '/bell',
    path: '/bell',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsHomeRoute =
  AuthenticatedSettingsHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/authenticated/bell': typeof AuthenticatedBellRoute
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/authenticated/bell': typeof AuthenticatedBellRoute
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/authenticated/bell': typeof AuthenticatedBellRoute
  '/authenticated/help': typeof AuthenticatedHelpRoute
  '/authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/authenticated/student': typeof AuthenticatedStudentRoute
  '/authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/authenticated/settings/bell': typeof AuthenticatedSettingsBellRoute
  '/authenticated/settings/home': typeof AuthenticatedSettingsHomeRoute
  '/authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/authenticated/bell'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/authenticated/bell'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/authenticated'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/authenticated/bell'
    | '/authenticated/help'
    | '/authenticated/settings'
    | '/authenticated/student'
    | '/authenticated/teacher'
    | '/authenticated/settings/bell'
    | '/authenticated/settings/home'
    | '/authenticated/settings/password'
    | '/authenticated/settings/profile'
    | '/authenticated/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/authenticated/bell': {
      id: '/authenticated/bell'
      path: '/bell'
      fullPath: '/authenticated/bell'
      preLoaderRoute: typeof AuthenticatedBellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/help': {
      id: '/authenticated/help'
      path: '/help'
      fullPath: '/authenticated/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/settings': {
      id: '/authenticated/settings'
      path: '/settings'
      fullPath: '/authenticated/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/student': {
      id: '/authenticated/student'
      path: '/student'
      fullPath: '/authenticated/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/teacher': {
      id: '/authenticated/teacher'
      path: '/teacher'
      fullPath: '/authenticated/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/authenticated/settings/bell': {
      id: '/authenticated/settings/bell'
      path: '/bell'
      fullPath: '/authenticated/settings/bell'
      preLoaderRoute: typeof AuthenticatedSettingsBellRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/home': {
      id: '/authenticated/settings/home'
      path: '/home'
      fullPath: '/authenticated/settings/home'
      preLoaderRoute: typeof AuthenticatedSettingsHomeRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/password': {
      id: '/authenticated/settings/password'
      path: '/password'
      fullPath: '/authenticated/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/settings/profile': {
      id: '/authenticated/settings/profile'
      path: '/profile'
      fullPath: '/authenticated/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/authenticated/users/$userId': {
      id: '/authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/authenticated/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBellRoute: typeof AuthenticatedSettingsBellRoute
  AuthenticatedSettingsHomeRoute: typeof AuthenticatedSettingsHomeRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBellRoute: AuthenticatedSettingsBellRoute,
  AuthenticatedSettingsHomeRoute: AuthenticatedSettingsHomeRoute,
  AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBellRoute: typeof AuthenticatedBellRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBellRoute: AuthenticatedBellRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
